### ISSUE TITLE
ルーム作成時のwebsocketによる通知

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#12]
ルーム作成時にwebsocketの通知はありますか？
https://github.com/shirasudon/go-chat/blob/master/chat/command_service.go#L57 を見る限り削除は通知されてるようなのですが。

**Comment by mzki** [comment]
websocketでの通知はchat/hub.goで行っています(HubImpl.eventSendingService)
ソースを見ると、現在のところ

* messageの作成
* クライアントのアクティブ化
* クライアントの非アクティブ化

の3つを通知しています

設計思想としては
pubsubから流れてきたeventを、どの範囲のユーザーに通知するか判断して送信しています

**Comment by mzki** [comment]
Support notification for more events

Currently websockets receives only 3 events:

* chat messages created
* client is activated
* client is inactivated

Now, support receiving more events:

* room created
* room deleted
* room added member
* ... etc.
