### ISSUE TITLE
ルーム作成時の通知のeventがunknown

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#15]
以下のコマンドでルームを作成しましたところ、
```
curl http://localhost:8080/chat/rooms -H "Content-Type: application/json" -X POST -d '{"sender_id": 2, "room_name": "hello there", "room_member_ids": [0,2,3]}'
```
通知の`event`が`unknown`になっています。
```
{event":"unknown","data":{"created_at":"2017-12-3… there","IsTalkRoom":false,"member_ids":[0,2,3]}}
```
これはこういう仕様でしょうか?こちらでどういうイベントか判断ができないので、できればeventにはルームを作成したことがわかるような名前を設定していただきたいです。

**Comment by hitochan777** [comment]
https://github.com/shirasudon/go-chat/blob/master/chat/json.go でクライアントに送るデータのフォーマットを決めてるのかな?

**Comment by mzki** [comment]
>https://github.com/shirasudon/go-chat/blob/master/chat/json.go でクライアントに送るデータのフォーマットを決めてるのかな?

はい。その通りです
`eventEncodeNames`に値を追加し忘れたのが原因です

必要な分だけ追加してもらっても構いませんが
今回のような抜け忘れが起こらない実装に置き換える予定です

**Comment by mzki** [comment]
修正しました

とりあえずテストで抜けを検知できるようにしました

**Comment by hitochan777** [comment]
ありがとう！
