### ISSUE TITLE
room_messages_read_by_user Websocket event is sent for every message

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#26]
@mzki 
When I send POST request to `/chat/rooms/2/messages/read`, the server seems to send `room_messages_read_by_user` for all the messages in a room.
I confirmed that the client sent the request only once.
Is this correct behavior?

**Comment by mzki** [comment]
@hitochan777  It is unexpected behavior.  I will survey the causes.

**Comment by mzki** [comment]
@hitochan777 the problem is fixed. close this issue.
