### ISSUE TITLE
Should StatusFound be StatusOK?

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#7]
`rest.go`で`StatusFound`を返している箇所がいくつかありますが、`StatusOK`を返すべきではないでしょうか?
間違っていたらすいません。

**Comment by mzki** [comment]
おっしゃる通り
`status ok`を返すべきです
修正します

`status found`の意味を誤解してました
リソースfoundではなく、redirect url found の意味みたいですね
