### ISSUE TITLE
"before" should be "time.Now()" by default?

### ISSUE THREAD

**Issue by hitochan777** [shirasudon/go-chat#8]
`chat/rooms/2/messages`にPOSTする際に`before`が指定されていない場合、`QueryRoomMessage`の`before`が`time.Time`のデフォルト値である`001-01-01 00:00:00 +0000 UTC`になっているようです。
もし可能であればでいいのですが、現在の時間(`time.Now()`)に指定していただけますか？

クライアントで毎回指定するようにすればいいのかもしれませんが、
クライアント側でbeforeに現在時間を指定した場合、リクエストがサーバーに届くまで間に届いたメッセージを取得できない問題が生じると思います。

**Comment by mzki** [comment]
実装します

懸念事項として、
`time.Time`のデフォルト値の場合は、time.Now()するという判断を
以下の、どの層に入れるべきか悩んでます
* Infra層 `/infra/inmemory/`
* HTTP層 `/`
* App層 `/chat/`

アプリケーションのロジックなのでApp層が有力かな？

**Comment by hitochan777** [comment]
そうですね。アプリケーション層が一番いい気がします。
